//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema.js";
import type { ModelResult as $ModelResult, TypeDefResult as $TypeDefResult } from "@zenstackhq/orm";
export type RolePermission = $ModelResult<$Schema, "RolePermission">;
export type User = $ModelResult<$Schema, "User">;
export type File = $ModelResult<$Schema, "File">;
export type RefreshToken = $ModelResult<$Schema, "RefreshToken">;
export type Class = $ModelResult<$Schema, "Class">;
export type ClassContent = $ModelResult<$Schema, "ClassContent">;
export type ClassContentComment = $ModelResult<$Schema, "ClassContentComment">;
export type ClassInvitation = $ModelResult<$Schema, "ClassInvitation">;
export type ClassMember = $ModelResult<$Schema, "ClassMember">;
export type Assignment = $ModelResult<$Schema, "Assignment">;
export type AssignmentSubmission = $ModelResult<$Schema, "AssignmentSubmission">;
export type Quiz = $ModelResult<$Schema, "Quiz">;
export type QuizAttempt = $ModelResult<$Schema, "QuizAttempt">;
export type Assessment = $ModelResult<$Schema, "Assessment">;
export type ClassAsset = $ModelResult<$Schema, "ClassAsset">;
export type Report = $ModelResult<$Schema, "Report">;
export type AssessmentScore = $ModelResult<$Schema, "AssessmentScore">;
export type ID = $TypeDefResult<$Schema, "ID">;
export type Timestamps = $TypeDefResult<$Schema, "Timestamps">;
export type Base = $TypeDefResult<$Schema, "Base">;
export type AuthInfo = $TypeDefResult<$Schema, "AuthInfo">;
export const Role = $schema.enums.Role.values;
export type Role = (typeof Role)[keyof typeof Role];
export const FileStatus = $schema.enums.FileStatus.values;
export type FileStatus = (typeof FileStatus)[keyof typeof FileStatus];
export const ClassRole = $schema.enums.ClassRole.values;
export type ClassRole = (typeof ClassRole)[keyof typeof ClassRole];
export const ClassAssetType = $schema.enums.ClassAssetType.values;
export type ClassAssetType = (typeof ClassAssetType)[keyof typeof ClassAssetType];
export const ReportType = $schema.enums.ReportType.values;
export type ReportType = (typeof ReportType)[keyof typeof ReportType];
export const ReportStatus = $schema.enums.ReportStatus.values;
export type ReportStatus = (typeof ReportStatus)[keyof typeof ReportStatus];
