//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, type AttributeApplication, type FieldDefault, ExpressionUtils } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "postgresql"
    } as const;
    models = {
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("nanoid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("nanoid") as FieldDefault
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                },
                username: {
                    name: "username",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                passwordHash: {
                    name: "passwordHash",
                    type: "String"
                },
                name: {
                    name: "name",
                    type: "String"
                },
                email: {
                    name: "email",
                    type: "String",
                    optional: true
                },
                role: {
                    name: "role",
                    type: "Role"
                },
                oidc_issuer: {
                    name: "oidc_issuer",
                    type: "String",
                    optional: true
                },
                oidc_userInfo: {
                    name: "oidc_userInfo",
                    type: "Json",
                    optional: true
                },
                oidc_sub: {
                    name: "oidc_sub",
                    type: "String",
                    unique: true,
                    optional: true,
                    attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
                },
                RefreshToken: {
                    name: "RefreshToken",
                    type: "RefreshToken",
                    array: true,
                    relation: { opposite: "User" }
                },
                File: {
                    name: "File",
                    type: "File",
                    array: true,
                    relation: { opposite: "User" }
                },
                Post: {
                    name: "Post",
                    type: "Post",
                    array: true,
                    relation: { opposite: "User" }
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("read") }, { name: "condition", value: ExpressionUtils.literal(true) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"]), "==", ExpressionUtils.field("id")) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                username: { type: "String" },
                oidc_sub: { type: "String" }
            }
        },
        File: {
            name: "File",
            fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                },
                key: {
                    name: "key",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }] as readonly AttributeApplication[]
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "User"
                    ] as readonly string[]
                },
                User: {
                    name: "User",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
                    relation: { opposite: "File", fields: ["userId"], references: ["id"] }
                },
                originalFilename: {
                    name: "originalFilename",
                    type: "String"
                },
                filename: {
                    name: "filename",
                    type: "String"
                },
                contentType: {
                    name: "contentType",
                    type: "String"
                },
                size: {
                    name: "size",
                    type: "Int",
                    optional: true
                },
                status: {
                    name: "status",
                    type: "FileStatus"
                },
                Post: {
                    name: "Post",
                    type: "Post",
                    array: true,
                    relation: { opposite: "Image" }
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"]), "==", ExpressionUtils.field("userId")) }] }
            ] as readonly AttributeApplication[],
            idFields: ["key"],
            uniqueFields: {
                key: { type: "String" }
            }
        },
        AuditLog: {
            name: "AuditLog",
            fields: {
                timestamp: {
                    name: "timestamp",
                    type: "DateTime",
                    id: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                cuid: {
                    name: "cuid",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                action: {
                    name: "action",
                    type: "String"
                },
                data: {
                    name: "data",
                    type: "Json"
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("DateTime", [ExpressionUtils.field("timestamp"), ExpressionUtils.field("cuid")]) }] },
                { name: "@@deny", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.literal(true) }] }
            ] as readonly AttributeApplication[],
            idFields: ["timestamp", "cuid"],
            uniqueFields: {
                timestamp_cuid: { timestamp: { type: "DateTime" }, cuid: { type: "String" } }
            }
        },
        RefreshToken: {
            name: "RefreshToken",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("nanoid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("nanoid") as FieldDefault
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "User"
                    ] as readonly string[]
                },
                User: {
                    name: "User",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
                    relation: { opposite: "RefreshToken", fields: ["userId"], references: ["id"] }
                },
                revoked: {
                    name: "revoked",
                    type: "Boolean"
                }
            },
            attributes: [
                { name: "@@deny", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.literal(true) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Post: {
            name: "Post",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("nanoid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("nanoid") as FieldDefault
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "User"
                    ] as readonly string[]
                },
                User: {
                    name: "User",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
                    relation: { opposite: "Post", fields: ["userId"], references: ["id"] }
                },
                content: {
                    name: "content",
                    type: "String"
                },
                imageKey: {
                    name: "imageKey",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "Image"
                    ] as readonly string[]
                },
                Image: {
                    name: "Image",
                    type: "File",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("imageKey")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("key")]) }] }] as readonly AttributeApplication[],
                    relation: { opposite: "Post", fields: ["imageKey"], references: ["key"] }
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("read") }, { name: "condition", value: ExpressionUtils.literal(true) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("create,update") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"]), "==", ExpressionUtils.field("userId")), "&&", ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("Image"), "==", ExpressionUtils._null()), "||", ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"]), "==", ExpressionUtils.member(ExpressionUtils.field("Image"), ["userId"])))) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("delete") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"]), "==", ExpressionUtils.field("userId")) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        }
    } as const;
    typeDefs = {
        ID: {
            name: "ID",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("nanoid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("nanoid") as FieldDefault
                }
            }
        },
        Timestamps: {
            name: "Timestamps",
            fields: {
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                }
            }
        },
        Base: {
            name: "Base",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("nanoid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("nanoid") as FieldDefault
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
                }
            }
        },
        AuthInfo: {
            name: "AuthInfo",
            fields: {
                id: {
                    name: "id",
                    type: "String"
                },
                username: {
                    name: "username",
                    type: "String"
                },
                role: {
                    name: "role",
                    type: "Role"
                }
            },
            attributes: [
                { name: "@@auth" }
            ] as readonly AttributeApplication[]
        }
    } as const;
    enums = {
        Role: {
            name: "Role",
            values: {
                ADMIN: "ADMIN",
                USER: "USER"
            }
        },
        FileStatus: {
            name: "FileStatus",
            values: {
                PENDING: "PENDING",
                UPLOADED: "UPLOADED",
                FAILED: "FAILED"
            }
        }
    } as const;
    authType = "AuthInfo" as const;
    plugins = {};
}
export const schema = new SchemaType();
