packages:
  - apps/*

catalog:
  '@zenstackhq/cli': 3.9.7
  '@zenstackhq/orm': 3.9.7
  '@zenstackhq/plugin-policy': 3.9.7
  '@zenstackhq/schema': 3.9.7
  '@zenstackhq/server': 3.9.7
  '@zenstackhq/tanstack-query': 3.9.7
  'zenstack-trpc': 0.2.5
  typescript: 6.0.3
  zod: 4.4.3

allowBuilds:
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
  protobufjs: true

onlyBuiltDependencies:
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - prisma
